---
name: Style checks

on:
  - pull_request
  - push

jobs:
  Black:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3.4.0

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"

      - name: Install requirements
        run: python3 -m pip install --requirement requirements-dev.txt

      - name: Run style checker
        run: black --check flask_blog/

  isort:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3.4.0

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"

      - name: Install requirements
        run: python3 -m pip install --requirement requirements-dev.txt

      - name: Run style checker
        run: isort --check flask_blog/
